### ISSUE TITLE
Ambiguity of "match"

### ISSUE THREAD

**Issue by JasonChatzitheodorou** [ZOrfeas/Llama-Compiler#3]
Θα έπρεπε να είναι αριστερά προσεταιριστικό ότι constructor μπαίνει σε αυτό. Για να γίνει αυτό χρειάζεται αλλαγή του συντακτικού.

Εναλλακτικά αφήνουμε τον προγραμματιστή να βάζει σωστά παρενθέσεις.

**Comment by ZOrfeas** [comment]
xD
